version: '3.8'

services:
  calculator-app:
    image: python:3.9-slim
    container_name: calculator-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "pip install flask &&
             python app.py"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
